### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by piede828** [fernandojsg/aframe-input-mapping-component#28]
Hi,

The last version of the example is not working for me. Events don't seem to be triggered and I got nothing in the console, even when using keyboard only.

**Comment by fernandojsg** [comment]
@piede828 I just pushed a new version, could you give it a try? https://fernandojsg.github.io/aframe-input-mapping-component/examples/basic

**Comment by fernandojsg** [comment]
I push a new release 0.1.3 and all the issues with the latest aframe should be fixed
