### ISSUE TITLE
[Question] using ArrowKey

### ISSUE THREAD

**Issue by arpu** [fernandojsg/aframe-input-mapping-component#29]
How can i set the ArrowKeys? 

for the keyboard mapping

**Comment by netpro2k** [comment]
Keyboard mappings are based on `KeyboardEvent.key` values. You can see a list here https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

Take the `KeyboardEvent.key` value from there, lowercase it, and add "_key". For example, the up arrow key is `ArrowUp` so you would add `arrowup_key` to your input mapping.

**Comment by arpu** [comment]
Thanks a lot for this Information. Works perfect!
