### ISSUE TITLE
Uglify error trying to run dist

### ISSUE THREAD

**Issue by arturitu** [fernandojsg/aframe-input-mapping-component#30]
I have multiple errors when I try to generate a new dist files. Maybe is needed to have uploaded some babel config files to the repo?

ERROR in aframe-input-mapping-component.min.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./src/activators/doublepress.js:14,0]

**Comment by fernandojsg** [comment]
fixed on https://github.com/fernandojsg/aframe-input-mapping-component/commit/f61d8513b06c19bbb5888c0fa32295c5b40d92be

thanks!
