### ISSUE TITLE
How to set orientation based on axis position after teleport?

### ISSUE THREAD

**Issue by machenmusik** [fernandojsg/aframe-input-mapping-component#8]
A common teleport mechanic now (robo recall, blade runner 2049, windows mixed reality) is for orientation after teleport to be set via axis position, and shown live while targeting.  How should that best be done with teleport-controls?

**Comment by fernandojsg** [comment]
I believe it's better to move that question to the `teleport` component repo: https://github.com/fernandojsg/aframe-teleport-controls/issues/44
